[2025-04-09T06:03:55.377+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-09T06:03:55.434+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_dag.hello_world manual__2025-04-09T06:03:44.180414+00:00 [queued]>
[2025-04-09T06:03:55.456+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_dag.hello_world manual__2025-04-09T06:03:44.180414+00:00 [queued]>
[2025-04-09T06:03:55.458+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-09T06:03:55.663+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): hello_world> on 2025-04-09 06:03:44.180414+00:00
[2025-04-09T06:03:55.683+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=74) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-09T06:03:55.693+0000] {standard_task_runner.py:72} INFO - Started process 76 to run task
[2025-04-09T06:03:55.696+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_dag', 'hello_world', 'manual__2025-04-09T06:03:44.180414+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/testdag.py', '--cfg-path', '/tmp/tmpspa570a7']
[2025-04-09T06:03:55.704+0000] {standard_task_runner.py:105} INFO - Job 4: Subtask hello_world
[2025-04-09T06:03:55.811+0000] {task_command.py:467} INFO - Running <TaskInstance: test_dag.hello_world manual__2025-04-09T06:03:44.180414+00:00 [running]> on host f1ffc118283c
[2025-04-09T06:03:55.920+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_dag' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2025-04-09T06:03:44.180414+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-09T06:03:44.180414+00:00'
[2025-04-09T06:03:55.927+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-09T06:03:55.942+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-09T06:03:55.948+0000] {logging_mixin.py:190} INFO - Current task name:hello_world state:running start_date:2025-04-09 06:03:55.435811+00:00
[2025-04-09T06:03:55.949+0000] {logging_mixin.py:190} INFO - Dag name:test_dag and current dag run status:running
[2025-04-09T06:03:55.950+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-09T06:03:55.961+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-04-09T06:03:55.966+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'Hello World!']
[2025-04-09T06:03:55.983+0000] {subprocess.py:99} INFO - Output:
[2025-04-09T06:03:56.010+0000] {subprocess.py:106} INFO - /usr/bin/bash: line 1: Hello: command not found
[2025-04-09T06:03:56.030+0000] {subprocess.py:110} INFO - Command exited with return code 127
[2025-04-09T06:03:56.190+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-09T06:03:56.206+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-09T06:03:56.209+0000] {logging_mixin.py:190} INFO - Task start:2025-04-09 06:03:55.435811+00:00 end:2025-04-09 06:03:56.204387+00:00 duration:0.768576
[2025-04-09T06:03:56.214+0000] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): hello_world> dag:<DAG: test_dag> dagrun:<DagRun test_dag @ 2025-04-09 06:03:44.180414+00:00: manual__2025-04-09T06:03:44.180414+00:00, state:running, queued_at: 2025-04-09 06:03:44.240217+00:00. externally triggered: True>
[2025-04-09T06:03:56.216+0000] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 127.
[2025-04-09T06:03:56.218+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=test_dag, task_id=hello_world, run_id=manual__2025-04-09T06:03:44.180414+00:00, execution_date=20250409T060344, start_date=20250409T060355, end_date=20250409T060356
[2025-04-09T06:03:56.310+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-09T06:03:56.313+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 4 for task hello_world (Bash command failed. The command returned a non-zero exit code 127.; 76)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-04-09T06:03:56.355+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-09T06:03:56.379+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
