[2025-04-13T03:46:31.620+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-13T03:46:31.658+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparktestdag.spark_submit_job manual__2025-04-13T03:46:25.587883+00:00 [queued]>
[2025-04-13T03:46:31.677+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparktestdag.spark_submit_job manual__2025-04-13T03:46:25.587883+00:00 [queued]>
[2025-04-13T03:46:31.678+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-13T03:46:31.899+0000] {taskinstance.py:2890} INFO - Executing <Task(SparkSubmitOperator): spark_submit_job> on 2025-04-13 03:46:25.587883+00:00
[2025-04-13T03:46:31.911+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-13T03:46:31.913+0000] {standard_task_runner.py:72} INFO - Started process 228 to run task
[2025-04-13T03:46:31.915+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sparktestdag', 'spark_submit_job', 'manual__2025-04-13T03:46:25.587883+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/sparktestdag.py', '--cfg-path', '/tmp/tmp2wm4daei']
[2025-04-13T03:46:31.917+0000] {standard_task_runner.py:105} INFO - Job 22: Subtask spark_submit_job
[2025-04-13T03:46:31.994+0000] {task_command.py:467} INFO - Running <TaskInstance: sparktestdag.spark_submit_job manual__2025-04-13T03:46:25.587883+00:00 [running]> on host 2ae87289320a
[2025-04-13T03:46:32.121+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sparktestdag' AIRFLOW_CTX_TASK_ID='spark_submit_job' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T03:46:25.587883+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-13T03:46:25.587883+00:00'
[2025-04-13T03:46:32.123+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-13T03:46:32.124+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-13T03:46:32.125+0000] {logging_mixin.py:190} INFO - Current task name:spark_submit_job state:running start_date:2025-04-13 03:46:31.660084+00:00
[2025-04-13T03:46:32.126+0000] {logging_mixin.py:190} INFO - Dag name:sparktestdag and current dag run status:running
[2025-04-13T03:46:32.127+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-13T03:46:32.143+0000] {spark_submit.py:305} INFO - Could not load connection string spark_master, defaulting to yarn
[2025-04-13T03:46:32.145+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark /pspark/testspark.py
[2025-04-13T03:46:33.688+0000] {spark_submit.py:645} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-04-13T03:46:33.689+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:650)
[2025-04-13T03:46:33.690+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:281)
[2025-04-13T03:46:33.690+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:237)
[2025-04-13T03:46:33.691+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:122)
[2025-04-13T03:46:33.692+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1108)
[2025-04-13T03:46:33.692+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1108)
[2025-04-13T03:46:33.693+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
[2025-04-13T03:46:33.694+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1125)
[2025-04-13T03:46:33.694+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1134)
[2025-04-13T03:46:33.694+0000] {spark_submit.py:645} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-04-13T03:46:33.717+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 196, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /pspark/testspark.py. Error code is: 1.
[2025-04-13T03:46:33.722+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-13T03:46:33.723+0000] {logging_mixin.py:190} INFO - Task start:2025-04-13 03:46:31.660084+00:00 end:2025-04-13 03:46:33.721896+00:00 duration:2.061812
[2025-04-13T03:46:33.724+0000] {logging_mixin.py:190} INFO - Task:<Task(SparkSubmitOperator): spark_submit_job> dag:<DAG: sparktestdag> dagrun:<DagRun sparktestdag @ 2025-04-13 03:46:25.587883+00:00: manual__2025-04-13T03:46:25.587883+00:00, state:running, queued_at: 2025-04-13 03:46:25.603383+00:00. externally triggered: True>
[2025-04-13T03:46:33.725+0000] {logging_mixin.py:190} INFO - Failure caused by Cannot execute: spark-submit --master yarn --name arrow-spark /pspark/testspark.py. Error code is: 1.
[2025-04-13T03:46:33.725+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=sparktestdag, task_id=spark_submit_job, run_id=manual__2025-04-13T03:46:25.587883+00:00, execution_date=20250413T034625, start_date=20250413T034631, end_date=20250413T034633
[2025-04-13T03:46:33.758+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-13T03:46:33.759+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 22 for task spark_submit_job (Cannot execute: spark-submit --master yarn --name arrow-spark /pspark/testspark.py. Error code is: 1.; 228)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 196, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark /pspark/testspark.py. Error code is: 1.
[2025-04-13T03:46:33.782+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-13T03:46:33.798+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-13T03:46:33.803+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
